### ISSUE TITLE
portability to other molecular simulation engines

### ISSUE THREAD

**Issue by pallavsen007** [molecularmodelingsection/TTMD#5]
Hi there, have gone through your paper, would want to use the technique for my work.
Is there any way I can use your code in any other molecular simulation engines other than ACEMD?

**Comment by molecularmodelingsection** [comment]
Hi,
thank you for showing interest in using our code.
Unfortunately, the current version only works with ACEMD, but, we are working on a new release where the codebase will get more modular, facilitating the implementation of different MD engines. 
At the moment, we are not working on implementing alternative engines ourselves, but we hope that the new release, which is coming soon, will facilitate new users in customizing the code for their needs. Anyway, ACEMD is free to use for academics if you use only a single GPU, you need to pay the license only if you are planning on using more than one device at the same time on a single machine. If you want to explore different MD engines, I would suggest trying OpenMM, since ACEMD is basically a front-end for it (most of the codebase is shared, plus it is heavily documented).
So, for now, I suggest you try the code as is, and wait for the next release.
