### ISSUE TITLE
ACEMD license error into conda TTMD environment

### ISSUE THREAD

**Issue by mglgc** [molecularmodelingsection/TTMD#7]
Hi,
Running TTMD jobs unsuccessfully end with some error messages about ACEMD expired license. The TTMD github doc page states that the ACEMD3 engine is already installed within the provided conda environment, so is it a required precondition to have one ACEMD license locally installed?
Thank you so much in advance for your reply.

**Comment by molecularmodelingsection** [comment]
Hi!
Due to an acemd3 3.5.0 bug, the license results as expired.
We have just updated a file with a working version.
You can download it directly and reinstall the correct env, or you can update manually acemd3 package version to 3.5.1 by typing (with ttmd as active env):
`conda update acemd3 -c acellera`

Thanks for reporting.
