### ISSUE TITLE
Leap errors using own ligands

### ISSUE THREAD

**Issue by mglgc** [molecularmodelingsection/TTMD#8]
Hi,
After a successful testing of the TTMD running using the example molecules under the test folder, we're getting some errors using our own ligand.mol2:

/.../conda/envs/ttmd/bin/teLeap: Fatal Error!
Could not open file ligand.frcmod: not found
  File "/../TTMD.py", line 6, in MAIN
    prepare_system()
  File "/../TTMD.py", line 854, in prepare_system
    addIonsRand COMPL Na+ {cations} Cl- {anions} 5
UnboundLocalError: local variable 'cations' referenced before assignment.

Please, could you point us to some fix? Thank you very much in advance for your reply.

**Comment by molecularmodelingsection** [comment]
Hi,
could you please provide us with the ligand.mol2 file so that we can test and see what's going on?
Most likely, a problem in the ligand preparation stage with antechamber leads to tleap not finding the required ligand.frcmod file.
MP

**Comment by mglgc** [comment]
You will find it attached. Thank you for your help.

    En martes, 23 de mayo de 2023 16:27:17 CEST, Molecular Modeling Section ***@***.***> escribió:  
 
 


Hi,
could you please provide us with the ligand.mol2 file so that we can test and see what's going on?
Most likely, a problem in the ligand preparation stage with antechamber leads to tleap not finding the required ligand.frcmod file.
MP

**Comment by molecularmodelingsection** [comment]
Hi,
Sorry but we can't find your ligand file.
Could you please attach it again or send it to mms.dsfarm.unipd@gmail.com ?
Thanks a lot
SM

**Comment by mglgc** [comment]
> Hi, Sorry but we can't find your ligand file. Could you please attach it again or send it to [mms.dsfarm.unipd@gmail.com](mailto:mms.dsfarm.unipd@gmail.com) ? Thanks a lot SM

I've just send it attached to that email address. Thank you so much.

**Comment by molecularmodelingsection** [comment]
Hi,
as expected, there is a problem with your ligand mol2 file that makes antechamber fails.

When I ran antechamber alone (antechamber -fi mol2 -i ligand.mol2 -o ligand_charged.mol2 -fo mol2 -nc -1 -c bcc -pf y -rn LIG) with the ligand file you provided to me it gave me this error:

"/home/mpavan/anaconda3/envs/ttmd/bin/wrapped_progs/antechamber: Fatal Error!
Weird atomic valence (5) for atom (ID: 47, Name: C29).
       Possible open valence."

If you check your ligand file, you will notice indeed that your C29 (carboxylic carbon) has a valence of 5, since it has two double bonds with the two carboxylic oxygens.

" 46   45   47  1
  47   47   48 2
  48   47   49 2"

This is not right, so antechamber will not let you go on with the partial charge calculation, hence why tleap cannot load the ligand.frcmod properly. You can either edit the ligand file manually (changing one of the two double bonds to a single one), or you can try to obtain a new mol2 file through a different path than the one that you followed the first time. In the future release that will come in the next months, we would most likely swap from mol2 to pdb for the ligand, as suggested in the AMBER forums by David Case himself (http://archive.ambermd.org/201706/0205.html).

There might be some other issues that are causing tleap to crash, however, since when the ligand's preparation does not go well usually the TTMD script carries on for a little bit and fails at later stages, but it is difficult to judge without further information. For the moment, let us know if it worked!

MP

**Comment by mglgc** [comment]
Thank you so much for your elaborated and useful reply.

**Comment by mglgc** [comment]
I was fixing the mol2 ligand file as you indicated. Additionally I was fixing some H atoms from 3 residues of the protein pdb file causing Leap fatal errors (on atom typing) and now I'm successfully running  the TTMD job.
